

export const BOOKRUNNER_MAPPINGS: Record<string, string> = {
    'bnpp': 'BNP Paribas',
    'bnpp (b&d)': 'BNP Paribas',
    'bnpp (gc/b&d)': 'BNP Paribas',
    'bnpp (gc)': 'BNP Paribas',
    'socgen': 'Société Générale',
    'socgen (b&d)': 'Société Générale',
    'socgen (gc)': 'Société Générale',
    'sg': 'Société Générale',
    'ca-cib': 'Crédit Agricole CIB',
    'ca-cib (gc)': 'Crédit Agricole CIB',
    'ca-cib (b&d)': 'Crédit Agricole CIB',
    'natixis': 'Natixis',
    'natixis (gc)': 'Natixis',
    'natixis (b&d)': 'Natixis',
    'barclays': 'Barclays',
    'barclays (gc)': 'Barclays',
    'barclays (b&d)': 'Barclays',
    'barclays (gc/b&d)': 'Barclays',
    'barc': 'Barclays',
    'barcs': 'Barclays',
    'ubs': 'UBS',
    'ubs (b&d)': 'UBS',
    'db': 'Deutsche Bank',
    'db (b&d)': 'Deutsche Bank',
    'db (gc)': 'Deutsche Bank',
    'db (gc/b&d)': 'Deutsche Bank',
    'deutsche bank': 'Deutsche Bank',
    'danske': 'Danske Bank',
    'danske bank': 'Danske Bank',
    'danske (b&d)': 'Danske Bank',
    'seb': 'SEB',
    'seb (gc)': 'SEB',
    'seb (b&d)': 'SEB',
    'nordea': 'Nordea',
    'nordea (b&d)': 'Nordea',
    'swedbank': 'Swedbank',
    'swedbank (b&d)': 'Swedbank',
    'rabobank': 'Rabobank',
    'rabo': 'Rabobank',
    'belfi': 'Belfius',
    'bmo': 'BMO Capital Markets',
    'bmo (b&d)': 'BMO Capital Markets',
    'boc': 'Bank of China',
    'bank of china': 'Bank of China',
    'bkcomm': 'Bank of Communications',
    'abc international': 'Agricultural Bank of China (IB)',
    'ccb': 'China Construction Bank',
    'cicc': 'China International Capital Corporation',
    'citic': 'CITIC',
    'china citic bank': 'CITIC',
    'china citic bank international': 'CITIC',
    'china merchants bank': 'China Merchants Bank',
    'huatai': 'Huatai International',
    'guotai junan international': 'Guotai Junan International',
    'jpm': 'JPMorgan',
    'jpm (b&d)': 'JPMorgan',
    'jpm (gc)': 'JPMorgan',
    'jpm (gc/b&d)': 'JPMorgan',
    'j.p. morgan': 'JPMorgan',
    'jpmorgan': 'JPMorgan',
    'bofa': 'Bank of America',
    'bofa (b&d)': 'Bank of America',
    'bofa (gc)': 'Bank of America',
    'bank of america': 'Bank of America',
    'citi': 'Citigroup',
    'citi (b&d)': 'Citigroup',
    'citi (gc)': 'Citigroup',
    'citi (gc/b&d)': 'Citigroup',
    'citigroup': 'Citigroup',
    'gs': 'Goldman Sachs',
    'gs (b&d)': 'Goldman Sachs',
    'gs (gc)': 'Goldman Sachs',
    'gsi': 'Goldman Sachs International',
    'ms': 'Morgan Stanley',
    'ms (b&d)': 'Morgan Stanley',
    'ms (gc)': 'Morgan Stanley',
    'morgan stanley': 'Morgan Stanley',
    'wfc': 'Wells Fargo Securities',
    'wfs': 'Wells Fargo Securities',
    'wfs (b&d)': 'Wells Fargo Securities',
    'wells fargo securities': 'Wells Fargo Securities',
    'usb': 'US Bancorp',
    'usb (b&d)': 'US Bancorp',
    'lloyds': 'Lloyds Bank',
    'lloyds (b&d)': 'Lloyds Bank',
    'natwest': 'NatWest',
    'natwest markets': 'NatWest Markets',
    'natwest markets (gc)': 'NatWest Markets',
    'hsbc': 'HSBC',
    'hsbc (gc)': 'HSBC',
    'hsbc (b&d)': 'HSBC',
    'stanchart': 'Standard Chartered',
    'stanchart (gc/b&d)': 'Standard Chartered',
    'standard chartered bank': 'Standard Chartered',
    'standard chartered bank (singapore) limited': 'Standard Chartered',
    'mizuho': 'Mizuho',
    'mizuho (b&d)': 'Mizuho',
    'mufg': 'MUFG',
    'mufg (gc)': 'MUFG',
    'smbc': 'SMBC',
    'smbc (b&d)': 'SMBC',
    'rbi': 'Raiffeisen Bank International',
    'cibccm': 'CIBC Capital Markets',
    'cibc': 'CIBC',
    'rbc': 'RBC Capital Markets',
    'rbccm': 'RBC Capital Markets',
    'rbccm (b&d)': 'RBC Capital Markets',
    'td': 'TD Securities',
    'tsi': 'TD Securities',
    'scotia': 'Scotiabank',
    'scotia (b&d)': 'Scotiabank',
    'anzltd': 'ANZ Banking Group',
    'anz': 'ANZ Banking Group',
    'nab': 'National Australia Bank',
    'national australia bank': 'National Australia Bank',
    'westpac': 'Westpac',
    'abn amro': 'ABN AMRO',
    'helaba': 'Helaba',
    'helaba (b&d)': 'Helaba',
    'erste': 'Erste Group',
    'erste (b&d)': 'Erste Group',
    'imi - intesa sanpaolo': 'Intesa Sanpaolo',
    'imi': 'Intesa Sanpaolo',
    'intesa sanpaolo': 'Intesa Sanpaolo',
    'unicredit': 'UniCredit',
    'unicredit (b&d)': 'UniCredit',
    'kbc': 'KBC',
    'kbc (gc)': 'KBC',
    'lbbw': 'LBBW',
    'lbbw (b&d)': 'LBBW',
    'nordlb': 'NordLB',
    'opbank': 'OP Corporate Bank',
    'opbank (b&d)': 'OP Corporate Bank',
    'dnb': 'DNB Bank',
    'dnbno': 'DNB Bank Norway',
    'dnb carnegie': 'DNB Markets / Carnegie',
    'pareto': 'Pareto Securities',
    'arctic': 'Arctic Securities',
    'sbmark / sb1': 'SpareBank 1 Markets',
    'mediobanca': 'Mediobanca',
    'banca akros': 'Banca Akros',
    'bbva': 'BBVA',
    'bbva (gc)': 'BBVA',
    'santander': 'Santander',
    'santander (b&d)': 'Santander',
    'santander (gc)': 'Santander',
    'itau bba': 'Itaú BBA',
    'balanz': 'Balanz Capital',
    'nykre': 'Nykredit'
};